### ISSUE TITLE
profile url no longer work

### ISSUE THREAD

**Issue by ipuneetsingh** [danillouz/devrant#1]
I tried profile url myself but its not working now.

https://www.devrant.io/api/users/dfox?&app=3

**Comment by danillouz** [comment]
The behaviour is correct. You're using the endpoint incorrectly. The api only allows you to fetch the user profile by it's **id** (and not by username like you're doing). You can only fetch the id by username. The module abstracts this for you so you can do something like `.profile('dfox')`.

The `profile` method makes two requests:
- Fetch `userId` by `username`; https://www.devrant.io/api/get-user-id?username=dfox&app=3
- Fetch profile by `userId`; https://www.devrant.io/api/users/487?app=3

**Comment by ipuneetsingh** [comment]
thanx, i managed to get the profile by user id with https://www.devrant.io/api/users/487?app=3

but didn't getting the endpoint for profile.

**Comment by ipuneetsingh** [comment]
i just saw index.js again and got the get-user-id. I think i missed it in hurry. 

Thnx once again

**Comment by danillouz** [comment]
No problem!
